redis: 
  host: localhost
  port: 6379
  password:

app: 
  port: 3000


google: 
  type: service_account
  project_id: sheets-307817
  private_key_id: edf342f4396b643c7bc9751d15620f255451d052
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeVxZoi+TvBv5z
    MzwiHgvSNcA0UxhismezpOhAilcoRad+gOStVljuubcor0hO3rgBau+49TnYiGrK
    aJP43t16UQ3CVGarNgTD/iB/LQKL8cIn6eiJtycI+vL8nY89fy7uhNMFDmN975Ac
    S73nox3I60YkCuO+RdOniX27TQUmMGq2VRnSubvDgjwlbSxJ0JeKDs4+N8Y+Bs0m
    wVri18lEXx4ZXHWPMEQIxmm9jX4JsdyXgVkqC8PandKGJjcxe502IUs3HD0ZLcL+
    OYwi8/evvHRGi5q+AE/iMtSCvO4EaaiB0upzD6xFkSdzfoqowMJzqES13HeaFsni
    Lrz+qvGrAgMBAAECggEAID6wDMRxFKtGfq2JBIen/jn2YIBGkpW+DWMWnbmSb1A+
    vM1znKHfrut3ISreiTWqqOX50zCZTYpnNmiZQSgNJb6YiLzV0PG6GjSCQP9llacf
    mctGAqbxvc8rKzCsg+Ysh8HympKeIjb6hugDKBNTb/6TAwojQkZ9Lhh2CBJg80sg
    AQObL+aqaV/q8nXQG/6qbr71gIG7+boZDovTS+L8f3pVxIw2+SPHEkVTqj5Z12dp
    tlAajX+wLmiGygrnzmzi74XAkHl7bIXWR6ClMJA/o8qQzCdPLP/I1/NST3FIMpS8
    v8zfnkAFmF1IAJsjYN3I6lMbjcXBm7JoCA+eRU38JQKBgQD5uTX3VDavXLfC5sow
    aBLMetto5n/qnDPfMq0yloj6F5hKHW0cLS67Kwf777Zikm46a6dMEv7XI85aBpgd
    aHsr5b5iry8orczZQ7AI7QW+vvD9fWUmos8+Op6/etggvYvTBJrsVjUJ4hlfDMnK
    riCv5JeHzq0W8EUjHXcMaUawtwKBgQDj7a9kHsNp6tscS+9zC7K2KRZ9BONNzxlb
    GiCGTsBUC1eDoLwedC4bEOHIRoiob0xUiiegXaBK42wJSIyjCPdbH1Hlk1Tm5lrf
    Gpn5eZQX/53jZMaH0GU0g99GzIOQa/iA96IajWWDarQDHyaFqlsSaGL8awj8SvRx
    3qbK99SqrQKBgHrGiXbRK5WqExq61ztXX66y1H7NnKRfKc2Zn7eYdT3oLdJ6hzNs
    L2aMMH+4CkaKUbFdTkJDsJFbpE90oIMM5EnfyWvBT4FDecxzz++DgOiX/enTJdEK
    CLRCo9vmbK4kIsObpwN9GtSCGhE2O1vvolh4HdwCS+1UMdmi2e37MGsfAoGAPhcY
    qWCMAUV+LOYus5tjMqZcvu/e7+pT0PJ8G7pGQF7alzvpIy6pBKyDpSg5wBCZrYn5
    I4F90gjD/H9r+FnP8F3G1JBfF4t3A8HeYgyRoDv9Cd4BCyxk9XpbD5FU4bnX92H+
    IdeU6Mjfgt4wg0cWChyvom2SBBBzKLXrn+0FXP0CgYEA+VfpGVFaTJMsQHuC87Ls
    WUXdgPo/7hh0qHv6rYXrEQj42EUu1MQI3Lpen5EXf52VGzBcJ4jtDFn/83/Dp7U9
    mWXZ+BGeipWBOYt7XM8Bc9ggUSA1+Firwwd/MLAkI9SJQb2era1vQBIPdqCatx2Z
    nGcDFRSi7izuFsBd6reYuaU=
    -----END PRIVATE KEY-----
  client_email: testsheets@sheets-307817.iam.gserviceaccount.com
  client_id: 116921501266716706356
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/testsheets%40sheets-307817.iam.gserviceaccount.com
  spreadsheetId: 1hWS0NlPHdqITo7IKR3_zIXDuniSjU3qzzgmKjZi_Xd8

google1:
  type: service_account
  project_id: sheets-307817
  private_key_id: b6c3ee6bd544c00e83f8ba6e8b912e3ff94dbd4c
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCh7lKfJJZz9Stf
    JwsO14Y9badHGtOsAdkjh1sn1VZzuAImZR6X74hNOQgwQEQKXc1ti/t5rUpj5Bc9
    1IaaFuS+MuVyOxXhVo1ybLutTAUL7AiofQruguwHd/wr+dUvNY8kQ71B4V7ZqcDD
    aqcpacTWNjBjqCBaSetrptkcDgAEfF1IF202illjXR/olcM1/lUPV0rXMOqRSw4M
    qZ5KD5YWXGyDXadMIMwhmC/4LraJP34wJx4oajSQKUVFULwJZD+PIA3nh90lRwtc
    XgJ6IwEqdAT/bwCZODW9/YoPTfr3iKN1z1HL6skc2LOUzPPNlI1ubefO1QMG3gNe
    iiu7+YNfAgMBAAECggEANw68QuYCzdx/abPxu5MmTn6ZEMEbVXGvbbgZE1sjMOdQ
    u9NH6qsD8hXBJf7D465vKZ8d2wpDr+Ee0eQP/BZqogzWHNfgIaT3JP+5dDvTv3D6
    pKcXb29OZ1+xexZQGOQiDleF4v+I64MfSpJZ0efniFoWa9v/XBOkGw845KQR93Py
    cANlyTiy5p94Mur8aqHukYPOuzfjxHhF/28SPtRSo8p5+YP/zSXEwvkqlpShVghJ
    uKb64hjYaJdsewUhoioxPtwDdfxsJeDqypdEBeJEw8L2v4O/AGHfGiXlQUGJfUBS
    eLzwbzgR5hwKrFSpL32V0oWqMmjLOKrPDnZnG7iTMQKBgQDhH7dnhBOWL/PO4N9L
    Q2z+KN5qJmccVWsGSIThJqFnwRBtZDcpBbvrB7u+2b4o2QQQgxYpLW+4HyJO/Eee
    ny3I+6ymV8mLGAIi5iO1Qwh+JDpeNPsY5E858tCrYclc7YEzU2xjfD5CfTf+qwxL
    zADl9OWnkwmP0UZOE5TKyDTk2QKBgQC4I9m5G23zCRsvS5LckaJ0g0CjZhIpLGBl
    +dQvQW6ZxegVRZGHWWmgCF1lDBzlBFgnF0UktuxZbkiJvHFdwk8lveL6Wd/1IPW4
    mDXWRbPDEqLP5ygzcBtAhKKrSaODV5cyoqD0rJCVlGGRZcp5G6iSQQx82LHBG6yN
    N6/X4Wym9wKBgQCnDBfVkiXOjeqGGkrW2ENqHP1dGv3sAl4WHX2sbDPcf2AnK/Pa
    VszoS6a+qWf3e4EOl5a8G2EI6OFWZtDmHQumVUn5bK66raf4KXlZqVIF9+/vs7SW
    9eLsBwdcBIWclQgIA+EruSehwrToHhhTrh8Eg8JdpDe2Jf3bNaB1EDZfkQKBgC28
    idmWXIrfGid3J/UtHyK9bxKmyZ/8a70ofnF2WRhMtcaCzxDFPp0HNttgVNT1bUfY
    Wc4yuSXFZLMBYU8ecjY3oeb4582k8CN3evfLvEiZmmL1UWDlWX9+8kCFO93lpaJo
    Dn53Vjow7sMEe3P1ULty+L0RvaTvUL6KtFx0m14lAoGBALAeZNPtMXEmh6OrNKNG
    o3KMFZWEBd9m5N/yh6doNucgKQ/BPC81iYbLY4+pHe9Zc2DnKtha/alnvOt99QDz
    7oLG8BFFosGG0pU+npldR1HuHLxcgO+pkdrDC90hew9++jKWSLPexajGyCR77w+O
    eX3iWDeeyvBfnGieKqWJBfDe
    -----END PRIVATE KEY-----
  client_email: test-662@sheets-307817.iam.gserviceaccount.com
  client_id: '105746746015189834286'
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/test-662%40sheets-307817.iam.gserviceaccount.com
  spreadsheetId: 1hZcvzkib0sVQqYpTwnQ-As4lT75FHXi51SgATDoVvJ4


jira: 
  host: prommoto.atlassian.net
  username: vladyslav.toloknov@gmail.com
  password: CCoW8QsYu40O9VtdJ5Gu7298
  

